  version: '3.9'
  services:
    backend:
      build:
        context: .
      ports:
        - 9000:3000 # map internal port 3000 to external 8000
        - 40000:40000 # map internal port 3000 to external 8000
      volumes:
        - .:/app:rw,delegated
      networks:
        - ambassador
      depends_on:
        - db
    db:
      image: mysql:8.1.0
      restart: always
      environment:
        MYSQL_DATABASE: ambassador
        MYSQL_USER: ambassador
        MYSQL_PASSWORD: ambassador_secret
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db/.dbdata:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/my.cnf
      ports:
        - 3307:3306
      networks:
        - ambassador

  networks:
    ambassador: # Define the network name as "ambassador"
      name: ambassador